import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#a78bfa" />
        <style>{`.kakao_ad_area { display: block !important; }`}</style>
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {/* 카카오 애드핏 광고 상단 */}
        <div style={{
          display: 'flex',
          justifyContent: 'center',
          position: 'fixed',
          top: 0,
          left: '50%',
          transform: 'translateX(-50%)',
          width: '100%',
          maxWidth: '28rem',
          zIndex: 50,
        }}>
          <ins
            className="kakao_ad_area"
            style={{ display: 'block', width: '100%' }}
            data-ad-unit="DAN-Xz4xE25ZdJKQpK76"
            data-ad-width="320"
            data-ad-height="50"
            data-ad-onfail="adfitTopOnFail"
          ></ins>
        </div>
        {/* NO-AD 콜백 등록 */}
        <Script id="adfit-noad-callbacks" strategy="afterInteractive">
          {`
            window.adfitTopOnFail = function(ins) {
              // 상단 광고 실패 시 동작
              console.log('상단 광고 노출 실패', ins);
            };
            window.adfitBottomOnFail = function(ins) {
              // 하단 광고 실패 시 동작
              console.log('하단 광고 노출 실패', ins);
            };
            // 광고가 숨겨지지 않도록 주기적으로 display: block 강제 적용
            setInterval(function() {
              document.querySelectorAll('.kakao_ad_area').forEach(function(el) {
                el.style.display = 'block';
              });
            }, 1000);
          `}
        </Script>
        <Script
          src="//t1.daumcdn.net/kas/static/ba.min.js"
          strategy="afterInteractive"
        />
        {children}
        {/* 카카오 애드핏 하단 배너 */}
        <div style={{
          display: 'flex',
          justifyContent: 'center',
          position: 'fixed',
          left: '50%',
          bottom: 0,
          transform: 'translateX(-50%)',
          width: '100%',
          maxWidth: '28rem',
          zIndex: 50,
        }}>
          <ins
            className="kakao_ad_area"
            style={{ display: 'block', width: '100%' }}
            data-ad-unit="DAN-lYOfiVolJOlJuE3a"
            data-ad-width="320"
            data-ad-height="50"
            data-ad-onfail="adfitBottomOnFail"
          ></ins>
        </div>
      </body>
    </html>
  );
}
